services:
  postgresql:
    image: postgres:14-alpine
    container_name: postgresql
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "wallet"
    ports:
      - "5432:5432"

  api:
    container_name: api-wallet
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=wallet
      - PORT=3000
    env_file: .env
    depends_on:
      - postgresql

volumes:
  pgdata: {}
